kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

